# Start from official AlmaLinux 9
FROM almalinux:9

# Metadata
LABEL maintainer="valerii.kholoimov@epfl.ch"
LABEL description="FairShip container on AlmaLinux 9 with aliBuild support"

# Switch to root to install dependencies
USER root

# Update system and install build tools, dev tools, and Python
RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled crb && \
    dnf groupinstall "Development Tools" -y && \
    dnf install --allowerasing -y \
        git \
        wget \
        tar \
        gzip \
        bzip2 bzip2-devel \
        make \
        cmake \
        gcc gcc-c++ \
        python3 python3-pip python3-devel \
        which \
        sudo \
        procps \
        xz \
        findutils \
        curl curl-devel \
        libX11-devel mesa-libGL-devel \
        rsync \
        ncurses-devel \
        byacc flex && \
    dnf clean all

# Install aliBuild
RUN pip3 install --upgrade pip && \
    pip3 install --user alibuild

RUN git clone https://github.com/ShipSoft/shipdist.git
RUN git clone https://github.com/ShipSoft/FairShip.git

RUN export SHIPDIST=shipdist/

RUN dnf -y install \
    libX11-devel \
    libXext-devel \
    libXft-devel \
    libXinerama-devel \
    mesa-libGL-devel \
    mesa-libGLU-devel \
    freeglut-devel \
    && dnf clean all

RUN dnf -y install \
    libXi-devel \
    libXrandr-devel \
    libXrender-devel \
    libXcursor-devel

# Add aliBuild to PATH
ENV PATH=/root/.local/bin:$PATH

# Set workdir and default entrypoint
ENTRYPOINT ["/bin/bash"]
